language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_5.0.gemfile
notifications:
  slack:
    secure: aVw4odRuPfoUjOXbmYfwhYrUuG0BPxmPDmpz6RmUoUKUtUDPWeCw60Xxv+AvGxNuc2usZ32eHW/tKXsQukx5SADVYkSgiAquo4/PErxAdt+P+ilEUT0fzJr8N11mtY0SEOK1iXVp5ucjswsjUYPyQwcddL/hBU2tcSU73yrLv2E=
sudo: false
