language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.3
before_script:
  - psql -c 'create database enju_news_dummy_test;' -U postgres
  - psql enju_biblio_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: aVw4odRuPfoUjOXbmYfwhYrUuG0BPxmPDmpz6RmUoUKUtUDPWeCw60Xxv+AvGxNuc2usZ32eHW/tKXsQukx5SADVYkSgiAquo4/PErxAdt+P+ilEUT0fzJr8N11mtY0SEOK1iXVp5ucjswsjUYPyQwcddL/hBU2tcSU73yrLv2E=
sudo: false
addons:
  postgresql: "9.4"
